### PR TITLE
[REF] Move RentalWizard and DateRangePicker xml to separate files

### PR DESCRIPTION
**Pull request by holdenrehg**
Issue https://github.com/Yenthe666/rental/issues/3

---

Moves component xml into stand alone files. Originally I was following the single component file pattern seen in a bunch of modern frontend frameworks ([including the Owl docs](https://github.com/odoo/owl/blob/master/doc/learning/how_to_write_sfc.md)) but when using Owl + Odoo the translations are not handled properly with single file components.

### CODE REVIEW

**Comment by Yenthe666** [comment]
🚫 This breaks & doesn't work as it cannot find the component. Recheck it please.
Besides of that I also think you have to re-generate the `.po` file due to the moves, no?

**Comment by holdenrehg** [comment]
I've dug through the core qweb rendering stuff pretty deeply this weekend and can't figure out what's happening @Yenthe666 .

As far as I can tell, the qweb files are getting loaded in properly on module update. They don't show up in Views on the backend because no qweb views do.

It looks like just the website side doesn't have access at all, despite loading the same owl js files on both the frontend and the backend. I've compared everything against the intro to owl module which work fine on the backend https://github.com/Oocademy/tutorials/tree/14.0/tutorial_intro_to_owl_part_1 . And also to a handful of Owl components in core Odoo that seem to work fine. I did notice that there don't seem to be any website components in core. Another reason why I'm thinking it's just not supported.

So feel like we're stuck between two issues here:
1. Single file components can't do translations.
2. Non single file component don't seem to be an option on website.

**Comment by Yenthe666** [comment]
Asked @ged-odoo about this one, I'm unsure 🤔

**Comment by ged-odoo** [comment]
Hey @Yenthe666 / @holdenrehg 
Yes, I see the problem. It is very stupid, and annoying. First, the problem is not owl itself: it is available to odoo frontend (it's easy to check, the owl global variable is defined in the console) (starting in 14.0).

The problem is in the template loading system. The reason is that historically, templates were only rendered server side (for website), so they are not loaded by the browser. Also, we only had one way to specify frontend templates (in the `qweb` key in the manifest). Because of that, it is kind of difficult to load templates files for now. There are some methods, but not very easy/satisfying: for example, load directly the xml file from the disk (but then, no xpath/translations will work), or create a controller that copy `load/qweb`, but it is possibly non trivial.

I am aware of the issue, and on that topic, it will get better: we revamped the asset system in odoo v15, and the load/qweb controller now takes an argument (the name of a bundle). The goal is to make it easy to define easily bundles (with css/js/xml) and load them where needed.

Now, for your problem, I just remembered yet another solution (not satisfying either, but may be a workaround in the meantime): define the templates in the js files, but with the `_t` for text that should be translated:

```js

const TEXT1 = _t('Some text');
const TEXT2 = _t('some other text);

const template = xml`<div><p>${TEXT1}</p><t-if="condition">${TEXT2}</t></div>`;

```
hope it helps, don't hesitate to ping me (even though I cannot promise I will answer :) )

**Comment by holdenrehg** [comment]
Thanks @ged-odoo that's a good enough workaround for now :)

**Pull request closed without merging**
