### PR TITLE
[REF] website_rentals: use _t for all text on components

### PR DESCRIPTION
**Pull request by holdenrehg**
https://github.com/Yenthe666/rental/issues/3

As per @ ged-odoo pointed out in https://github.com/Yenthe666/rental/pull/5 , we must pass all strings through the `_t` function for translations on our components.

Added an alias on each component for `_t`:
```js
const _t = require('web.core')._t;

class TheComponent extends Component {
    // alias to web.core._t translation fn
    _t(str) { return _t(str); }
}
```

Then updated every reference to text data in the template via:
```xml
<span t-esc="_t('Label')">
<span t-esc="_t(state.someData)"/>
```

### CODE REVIEW

**Comment by Yenthe666** [comment]
@holdenrehg hmm I did a test but they still do not seem to translate and show up in another lang?
Here's a test I did:
image

You can just test it on your local db by activating both languages (both frontend and backend) and then switching the language in the website. The translation sources are available for FR & CH (Deutsch) so you could test with both langs.

**Comment by holdenrehg** [comment]
Yep, tested with French. As long as the terms are defined it's working on my end:

**Comment by holdenrehg** [comment]
Alright I found something.

So there doesn't look like there's any issue with the `_t` function on the frontend, since _some_ terms were getting translated.

I drilled down into the term "Quantity" for `fr` since it was translating correctly. I deleted all terms out of the frontend until I found the one that was getting triggered properly and it's this one:

https://github.com/odoo/odoo/blob/14.0/addons/website_sale/i18n/fr.po#L2459-L2466

So I basically followed the same format for the "to" term in our `.po` file (which previously was not working), updated terms, and now it works fine. No change to the js.

Thinking we just need to update the `.po` file.

```
#. module: website_rentals
#. openerp-web
#: code:addons/website_sale/static/src/xml/website_sale_dashboard.xml:0
#: model_terms:ir.ui.view,arch_db:website_sale.cart_lines
#: model_terms:ir.ui.view,arch_db:website_sale.cart_summary
#, python-format
msgid "to"
msgstr "à"
```

**Comment by Yenthe666** [comment]
Added all terms in https://github.com/Yenthe666/rental/commit/3c30a16ef446a8a22b35f7b69d00c92241c6d891
There's two issues in my opinion:
1. Odoo doesn't auto-generate the terms from OWL dialogs and thus they do not show up in the `.po` file
2. Odoo doesn't correctly load translated terms from OWL dialogs if it is not a major lang (e.g `de` as a language and translation works, while `de_CH` does not).

**Pull request closed without merging**
